### ISSUE TITLE
binocular toroids

### ISSUE THREAD

**Issue by NelsonSet** [sh123/nano_swr_meter#1]
Hi, what material mix did you use for the binocular toroids?

**Comment by sh123** [comment]
I did not have binocular toroids, was using two unmarked noname cores found in junk box, was measuring them with VNA analyzer they were close to mix 52, perhaps 43

https://github.com/sh123/nano_swr_meter/raw/master/extras/images/cores.jpg

**Comment by NelsonSet** [comment]
Thanks for the info, I will try 43 mix as I have some in my junk box. Cheers ;-)
